### ISSUE TITLE
Download Link for Superfish is Broken

### ISSUE THREAD

**Issue by congunter** [ChristopherMayes/pySuperfish#2]
Is there another link that gets you to the download page? The current one is broken. Thanks!

**Comment by ChristopherMayes** [comment]
I currently see:
```
System Unavailable
We are currently performing scheduled maintenance.
```

Perhaps we check in a day or so.

**Comment by congunter** [comment]
Unfortunately, it is still unavailable. I wonder if they revoked public access.

**Comment by ChristopherMayes** [comment]
@congunter Perhaps try to contact them?

**Comment by alkucich** [comment]
> Is there another link that gets you to the download page? The current one is broken. Thanks!

Hi there, I know your comment is from a while ago so IDK if this is still relevant, but after 2 days of scouring the internet because I wanted to use Superfish for a university class project, I found this mirrorlink from a NASA spaceflight forum from 2015.  In no way do I officially endorse this link because it came from a random person on the internet, but I don't seem to have any malware yet LOL.  If you wanna roll the dice, this link worked for me

http://hallaweb.jlab.org/12GeV/SoLID/download/field/PoissonSuperfish_7.18.exe

**Comment by ChristopherMayes** [comment]
This is noted now in the main readme: https://github.com/ChristopherMayes/PySuperfish?tab=readme-ov-file#pysuperfish
